# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

  {{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "aether-roc-gui.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - secretName: {{ template "aether-roc-gui.fullname" . }}-secret
      hosts:
        - aether-roc-gui.onosproject.org
  rules:
    - host: aether-roc-gui.onosproject.org
      http:
        paths:
          - backend:
              serviceName: {{ template "aether-roc-gui.fullname" . }}
              servicePort: web
  {{- end }}
