# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "aether-roc-gui.fullname" . }}-access-services
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "aether-roc-gui.fullname" . }}-service-role
  apiGroup: rbac.authorization.k8s.io
