# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: {{ template "onos-e2t.fullname" . }}-channels
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "onos-e2t.store.consensus.name" . }}
    {{- end }}
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: {{ template "onos-e2t.fullname" . }}-subscriptions
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "onos-e2t.store.consensus.name" . }}
    {{- end }}