apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: {{ template "onos-e2t.fullname" . }}-objects
  namespace: {{ .Release.Namespace }}
spec:
  store:
    {{- if .Values.global.store.consensus.enabled }}
    name: {{ template "global.store.consensus.name" . }}
    {{- else }}
    name: {{ template "onos-e2t.store.consensus.name" . }}
    {{- end }}