# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "onos-e2t.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "onos-e2t.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "onos-e2t.fullname" . }}
  apiGroup: rbac.authorization.k8s.io