# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "onos-e2t.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  verbs:
  - '*'