# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-e2t.fullname" . }}
  labels:
    app: {{ template "onos-e2t.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-e2t.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    name: {{ template "onos-e2t.fullname" . }}
    app: onos
    type: e2t
    resource: {{ template "onos-e2t.fullname" . }}
    {{- include "onos-e2t.selectorLabels" . | nindent 4 }}
  ports:
    - name: sctp
      port: {{ .Values.service.e2.port | default 36421 }}
      protocol: {{ .Values.service.e2.protocol }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onos-e2t.fullname" . }}-hs
  labels:
    app: {{ template "onos-e2t.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-e2t.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    name: {{ template "onos-e2t.fullname" . }}
    app: onos
    type: e2t
    resource: {{ template "onos-e2t.fullname" . }}
    {{- include "onos-e2t.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpc.port }}
---
{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-e2t.fullname" . }}-external
  labels:
    app: {{ template "onos-e2t.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-e2t.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    name: {{ template "onos-e2t.fullname" . }}
    app: onos
    type: e2t
    resource: {{ template "onos-e2t.fullname" . }}
    {{- include "onos-e2t.selectorLabels" . | nindent 4 }}
  ports:
    - name: sctp
      port: {{ .Values.service.e2.port }}
      nodePort: {{ .Values.service.e2.nodePort }}
      protocol: {{ .Values.service.e2.protocol }}
{{- end }}
