# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: onos-e2t
description: ONOS E2 Termination
kubeVersion: ">=1.17.0"
type: application
version: 1.4.11
appVersion: v0.11.7
keywords:
  - onos
  - sdn
  - ric
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
