# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "onos-ric.fullname" . }}
  labels:
    {{- include "onos-ric.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      name: {{ template "onos-ric.fullname" . }}
      app: onos
      type: ran
      resource: {{ template "onos-ric.fullname" . }}
      {{- include "onos-ric.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "onos-ric.fullname" . }}-hs
  template:
    metadata:
      labels:
        name: {{ template "onos-ric.fullname" . }}
        app: onos
        type: ran
        resource: {{ template "onos-ric.fullname" . }}
        {{- include "onos-ric.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: onos-ric
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: configure
          image: ubuntu:16.04
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/sh", "-c", "printf \"%s.%s\" $(hostname -s) $(hostname -d) >> /config/id"]
          volumeMounts:
            - name: pod-id
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "onos-ric.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # *_NAMESPACE and *_NAME environment variables are recognized by onos-lib-go utilities.
            # These variables should always be defined.
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ template "onos-ric.fullname" . }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - sh
            - -c
            - "POD_ID=$(cat /etc/onos/pod/id) onos-ric"
          args:
            - "-caPath=/etc/onos/certs/tls.cacrt"
            - "-keyPath=/etc/onos/certs/tls.key"
            - "-certPath=/etc/onos/certs/tls.crt"
            - "-topoEndpoint={{ .Values.topoEndpoint }}"
            - "-enableMetrics={{ .Values.enableMetrics }}"
          ports:
            - name: grpc
              containerPort: 5150
            {{- if .Values.debug }}
            - name: debug
              containerPort: 40000
              protocol: TCP
            {{- end }}
          startupProbe:
            tcpSocket:
              port: 5150
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/onos/config
              readOnly: true
            - name: secret
              mountPath: /etc/onos/certs
              readOnly: true
            - name: pod-id
              mountPath: /etc/onos/pod
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Enable ptrace for debugging
          securityContext:
            {{- if .Values.debug }}
            capabilities:
              add:
                - SYS_PTRACE
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "onos-ric.fullname" . }}-config
        - name: pod-id
          emptyDir: {}
        - name: secret
          secret:
            secretName: {{ template "onos-ric.fullname" . }}-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
