# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


{{- if index .Values "import" "prometheus-stack" "enabled" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasource
  labels:
     grafana_datasource: "1"
data:
  datasources-{{ .Release.Name }}.yaml: |-
    apiVersion: 1
    datasources:
{{- range index .Values "grafana" "prometheus-datasources" }}
    - name: {{ .name }}
      type: prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: false
      url: {{ .endpoint }}
{{- end }}
{{- range index .Values "grafana" "opensearch-datasources" }}
    - name: {{ .name }}
      url: {{ .endpoint }}
      type: grafana-opensearch-datasource
      access: proxy
      database: 'fluentbit-*'
      basicAuth: true
      basicAuthUser: "admin"
      basicAuthPassword: "admin"
      jsonData:
        timeField: "@timestamp"
        logMessageField: log
        logLevelField: logLevel
        pplEnabled: true
        tlsSkipVerify: true
{{- end }}

{{- end }}