# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: sd-ran
description: Umbrella chart to deploy all ONOS-RIC and simulator
kubeVersion: ">=1.17.0"
type: application
version: 1.3.217
appVersion: v1.3.0
keywords:
  - onos
  - sdn
  - ran
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
dependencies:
  - name: nem-monitoring
    condition: import.nem-monitoring.enabled
    repository: https://charts.opencord.org
    version: 1.3.20
  - name: onos-e2t
    condition: import.onos-e2t.enabled
    repository: file://../onos-e2t
    version: 1.3.4
  - name: onos-a1t
    condition: import.onos-a1t.enabled
    repository: file://../onos-a1t
    version: 0.1.2
  - name: onos-o1t
    condition: import.onos-o1t.enabled
    repository: file://../onos-o1t
    version: 0.2.1
  - name: onos-topo
    condition: import.onos-topo.enabled
    repository: https://charts.onosproject.org
    version: 1.2.2
  - name: onos-uenib
    condition: import.onos-uenib.enabled
    repository: file://../onos-uenib
    version: 1.2.1
  - name: onos-config
    condition: import.onos-config.enabled
    repository: https://charts.onosproject.org
    version: 1.6.4
  - name: config-model-ric-1-0-0
    condition: onos-config.models.ric.v1.enabled
    repository: file://../config-models/ric-1.x
    version: 1.0.4
  - name: onos-gui
    condition: import.onos-gui.enabled
    repository: https://charts.onosproject.org
    version: 1.0.7
  - name: ran-simulator
    condition: import.ran-simulator.enabled
    repository: file://../ran-simulator
    version: 1.3.5
  - name: onos-cli
    condition: import.onos-cli.enabled
    repository: https://charts.onosproject.org
    version: 1.2.6
  - name: onos-kpimon
    condition: import.onos-kpimon.enabled
    repository: file://../onos-kpimon
    version: 0.8.2
  - name: onos-pci
    condition: import.onos-pci.enabled
    repository: file://../onos-pci
    version: 0.8.2
  - name: fb-kpimon-xapp
    condition: import.fb-kpimon-xapp.enabled
    repository: file://../fb-kpimon-xapp
    version: 0.0.6
  - name: fb-ah-xapp
    condition: import.fb-ah-xapp.enabled
    repository: file://../fb-ah-xapp
    version: 0.0.14
  - name: fb-ah-gui
    condition: import.fb-ah-gui.enabled
    repository: file://../fb-ah-gui
    version: 0.0.5
  - name: onos-mho
    condition: import.onos-mho.enabled
    repository: file://../onos-mho
    version: 0.2.1
  - name: onos-rsm
    condition: import.onos-rsm.enabled
    repository: file://../onos-rsm
    version: 0.1.6
  - name: onos-mlb
    condition: import.onos-mlb.enabled
    repository: file://../onos-mlb
    version: 0.2.1
  - name: ah-eson-test-server
    condition: import.ah-eson-test-server.enabled
    repository: file://../ah-eson-test-server
    version: 0.0.4
  - name: fluent-bit
    condition: import.fluent-bit.enabled
    version: 0.15.4
    repository: https://fluent.github.io/helm-charts
  - name: opendistro-es
    condition: import.opendistro-es.enabled
    version: 1.13.0
    repository: https://lukasmrtvy.github.io/opendistro/
  - name: kube-prometheus-stack
    condition: import.prometheus-stack.enabled
    version: 14.5.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: onos-exporter
    condition: import.onos-exporter.enabled
    version: 0.4.1
    repository: file://../onos-exporter
