apiVersion: v2
name: sd-ran
description: Umbrella chart to deploy all ONOS-RIC and simulator
kubeVersion: ">=1.17.0"
type: application
version: 0.0.11
appVersion: v0.6.6
keywords:
  - onos
  - sdn
  - ran
home: https://onosproject.org
maintainers:
  - name: Woojoong Kim
    email: woojoong@opennetworking.org
  - name: Jordan Halterman
    email: jordan@opennetworking.org
dependencies:
  - name: nem-monitoring
    condition: import.nem-monitoring.enabled
    repository: https://charts.opencord.org
    version: 1.3.15
  - name: atomix-controller
    condition: import.atomix-controller.enabled
    repository: https://charts.atomix.io
    version: 0.5.1
  - name: raft-storage-controller
    condition: import.atomix-raft-storage-controller.enabled
    repository: https://charts.atomix.io
    version: 0.4.0
  - name: onos-ric
    condition: import.onos-ric.enabled
    repository: file://../onos-ric
    version: 0.0.8
  - name: onos-ric-ho
    condition: import.onos-ric-ho.enabled
    repository: file://../onos-ric-ho
    version: 0.0.6
  - name: onos-ric-mlb
    condition: import.onos-ric-mlb.enabled
    repository: file://../onos-ric-mlb
    version: 0.0.6
  - name: onos-topo
    condition: import.onos-topo.enabled
    repository: https://charts.onosproject.org
    version: 0.0.5
  - name: onos-config
    condition: import.onos-config.enabled
    repository: https://charts.onosproject.org
    version: 0.0.6
  - name: onos-gui
    condition: import.onos-gui.enabled
    repository: https://charts.onosproject.org
    version: 0.0.4
  - name: ran-simulator
    condition: import.ran-simulator.enabled
    repository: file://../ran-simulator
    version: 0.0.6
  - name: onos-sdran-cli
    condition: import.onos-sdran-cli.enabled
    repository: file://../onos-sdran-cli
    version: 0.0.4
