# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-sdran-cli.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/configs/*.yaml").AsConfig | indent 2 }}
