# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onos-sdran-cli.fullname" . }}
  labels:
    {{- include "onos-sdran-cli.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "onos-sdran-cli.fullname" . }}
      app: onos
      type: cli
      resource: {{ template "onos-sdran-cli.fullname" . }}
      {{- include "onos-sdran-cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "onos-sdran-cli.fullname" . }}
        app: onos
        type: cli
        resource: {{ template "onos-sdran-cli.fullname" . }}
        {{- include "onos-sdran-cli.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "onos-sdran-cli.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin : true
          volumeMounts:
            - name: config
              mountPath: /home/onos/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "onos-sdran-cli.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
