# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-pci.fullname" . }}
  labels:
    app: {{ template "onos-pci.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- include "onos-pci.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    name: {{ template "onos-pci.fullname" . }}
    app: onos
    type: pci
    resource: {{ template "onos-pci.fullname" . }}
  {{- include "onos-pci.selectorLabels" . | nindent 4 }}
  ports:
    - name: exporter
      port: {{ .Values.service.exporter.port }}
    - name: grpc
      port: {{ .Values.service.grpc.port}}
    - name: gnmi
      port: {{.Values.service.gnmi.port}}

  {{- if .Values.service.exporter.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-pci.fullname" . }}-external
  labels:
    app: {{ template "onos-pci.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- include "onos-pci.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    name: {{ template "onos-pci.fullname" . }}
    app: onos
    type: pci
    resource: {{ template "onos-pci.fullname" . }}
  {{- include "onos-pci.selectorLabels" . | nindent 4 }}
  ports:
    - name: exporter
      port: {{ .Values.service.exporter.port }}
      nodePort: {{ .Values.service.exporter.nodePort.port }}
      protocol: TCP
  {{- end }}
---

