# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-e2sub.fullname" . }}
  labels:
    app: {{ template "onos-e2sub.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-e2sub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    name: {{ template "onos-e2sub.fullname" . }}
    app: onos
    type: e2sub
    resource: {{ template "onos-e2sub.fullname" . }}
    {{- include "onos-e2sub.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 5150
    - name: exporter
      port: 7001
---
{{- if .Values.service.external.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-e2sub.fullname" . }}-external
  labels:
    app: {{ template "onos-e2sub.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-e2sub.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    name: {{ template "onos-e2sub.fullname" . }}
    app: onos
    type: e2sub
    resource: {{ template "onos-e2sub.fullname" . }}
    {{- include "onos-e2sub.selectorLabels" . | nindent 4 }}
  ports:
    - name: exporter
      port: 7001
      nodePort: {{ .Values.service.external.nodePort }}
      protocol: TCP
{{- end }}
