# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: {{ .Release.Namespace }}
data:
  alertmanager.yml: |-
    global: {}
      # slack_api_url: ''

    receivers:
      - name: default-receiver
        webhook_configs:
        - url: {{ .Values.prometheus.alertmanager.webhook_url }}

    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
