# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# Default values for onos-a1t.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    registry: ""
    tag: ""

replicaCount: 1

image:
  registry: ""
  repository: onosproject/onos-a1t
  tag: '{{ .Chart.AppVersion }}'
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-a1t"

storage: {}

service:
  # TODO: External NodePort service should be disabled by default
  grpc:
    port: 5150
  gnmi:
    port: 9339
  a1ap:
    port: 9639
    nodePort:
      enabled: true
      port: 31963
  exporter:
    port: 7001
    nodePort:
      enabled: false
      port: 31701

config:
  a1t:
    a1ap:
      port: 5150
      baseURL: "0.0.0.0:9639"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
