# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ah-eson-test-server.fullname" . }}
  labels:
    {{- include "ah-eson-test-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "ah-eson-test-server.fullname" . }}
      app: ah-eson-test-server
      type: ah-eson-test-server
      resource: {{ template "ah-eson-test-server.fullname" . }}
      {{- include "ah-eson-test-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "ah-eson-test-server.fullname" . }}
        app: ah-eson-test-server
        type: ah-eson-test-server
        resource: {{ template "ah-eson-test-server.fullname" . }}
        {{- include "ah-eson-test-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: ah-eson-test-server
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          command: {{ .Values.command }}
          args:
            - "--port=[::]:{{ .Values.servicePort }}"
            - "--service_port={{ .Values.servicePort }}"
            - '--service_hostname={{ template "ah-eson-test-server.fullname" . }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: tcp
              containerPort: {{ .Values.servicePort }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.servicePort }}
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 10

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
