# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v2
name: onos-sdran-cli
description: ONOS Command Line Interface
kubeVersion: ">=1.17.0"
type: application
version: 1.0.0
appVersion: v0.7.0
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
