{
 "title": "SD-RAN KPIs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "onos kpimon",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum (onos_xappkpimon_rrc_conn_avg) by (cellid)",
     "legendFormat": "{{cellid}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "fb kpimon ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xappkpimon_rrc_conn_avg" }
   ]
  },
  {
   "title": "Number of users (in RRC connected mode) per cell ID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (onos_xappkpimon_rrc_conn_avg) by (cellid)",
     "legendFormat": "{{cellid}}"
    }
   ]
  },
  { "title": "PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "onos pci conflicts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "onos_xapppci_conflicts" }
   ]
  },
  { "title": "E2T", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "List of Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "onos_e2t_connections", "legendFormat": "ID:{{id}} / PLMNID:{{plmnid}}" }
   ]
  },
  { "title": "TOPO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Entities by Kind",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count (onos_topo_entities) by (kind)",
     "legendFormat": "{{kind}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Relations by Kind",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (onos_topo_relations) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "List of Entities (kind: entity ID)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onos_topo_entities", "legendFormat": "{{kind}}: {{entityid}}" }
   ]
  },
  {
   "title": "List of Relations (source - kind - target)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_topo_relations",
     "legendFormat": "{{source}} - {{kind}} - {{target}}"
    }
   ]
  }
 ]
}