# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

topodevices:
- id: spgw-1
  address: sdcore-adapter:5150
  version: 1.0.0
  type: Aether
  attributes:
    grpcport: "5150"
  displayname: SPGW-1
