# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

topokinds:
  - id: "Aether"
    type: 3
    obj:
      kind:
        name: "Aether"
    attributes:
      displayname: ""
      address: ""
      version: ""
      tls-insecure: ""
topoentities:
  - id: connectivity-service-v2
    type: 1
    obj:
      entity:
        kindid: "Aether"
    attributes:
      version: "2.1.0"
      displayname: "SPGW 1"
      address: "sdcore-adapter:5150"
      latitude: "52.5150"
      longitude: "13.3885"
      tls-insecure: "true"
      grpcport: "5150"