# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

# Default values for fb-ah-xapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onosproject/fb-ah-xapp
  tag: 0.0.1
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "fb-ah-xapp"

storage: {}

config:
  servicePath: "/etc/onos/config"
  ric:
    e2tEndpoint: "onos-e2t:5150"
    topoEndpoint: "onos-topo:5150"
  esonEndpoint: "ah-eson-test-server:51050"
  esonSubscribeEnabled: true
  # 0 or unspecified means report triggered upon change
  indicationTriggerPeriodicSeconds: 0
  # 0 or unspecified means no artificial delay in processing indication messages (useful for demo)
  processingDelay: 0
  # period of update of capacity information to eson (seconds)
  capacityUpdatePeriod: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
