# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ran-simulator.fullname" . }}-config
  labels:
    app: {{ template "ran-simulator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  model.yaml: |-
  {{ .Files.Get "files/model/model.yaml" | indent 4}}
  pci.yaml: |-
  {{ .Files.Get "files/metrics/pci.yaml" | indent 4}}
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}

