# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ran-simulator
  namespace: {{ .Release.Namespace }}
