# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-post
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/configs/*.yaml").AsConfig | indent 2 }}
