# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-job-post-install-topo"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-job-post-install-topo"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        {{- if index .Values "import" "onos-topo" "enabled" }}
          {{- if index .Values "onos-sdran-cli" "postInstall" "toponew"}}
        - name: post-install-topo-new-job
          image: {{ index .Values "onos-sdran-cli" "image" "repository" }}:{{ index .Values "onos-sdran-cli" "image" "tag" }}
          imagePullPolicy: {{ index .Values "onos-sdran-cli" "image" "pullPolicy" }}
          command: ["/usr/local/bin/sdran"]
          args:
          - "topo"
          - "load"
          - "yamlentities"
          - {{ index .Values "onos-sdran-cli" "postInstall" "toponew" }}
          volumeMounts:
            - name: config
              mountPath: /home/onos
              readOnly: true
          {{- end }}
        {{- end }}
        {{- if index .Values "import" "onos-topo" "enabled" }}
          {{- if index .Values "onos-sdran-cli" "postInstall" "topo"}}
        - name: post-install-topo-job
          image: {{ index .Values "onos-sdran-cli" "image" "repository" }}:{{ index .Values "onos-sdran-cli" "image" "tag" }}
          imagePullPolicy: {{ index .Values "onos-sdran-cli" "image" "pullPolicy" }}
          command: ["/usr/local/bin/sdran"]
          args:
          - "topo"
          - "load"
          - "yaml"
          - {{ index .Values "onos-sdran-cli" "postInstall" "topo" }}
          volumeMounts:
            - name: config
              mountPath: /home/onos
              readOnly: true
          {{- end }}
        {{- end }}
        {{- if index .Values "import" "onos-config" "enabled" }}
          {{- if index .Values "onos-sdran-cli" "postInstall" "config" }}
        - name: post-install-config-job
          image: {{ index .Values "onos-sdran-cli" "image" "repository" }}:{{ index .Values "onos-sdran-cli" "image" "tag" }}
          imagePullPolicy: {{ index .Values "onos-sdran-cli" "image" "pullPolicy" }}
          command: ["/usr/local/bin/sdran"]
          args:
            - "config"
            - "load"
            - "yaml"
            {{- with index .Values "onos-sdran-cli" "postInstall" "config" }}
            {{- range $filename := . }}
            - {{ $filename }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /home/onos
              readOnly: true
          {{- end }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-post
