# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# A topology kind representing an E2 node
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: e2node
spec:
  aspects:
    onos.topo.Location:
      lat: 50.08834
      lng: 14.40372
    onos.topo.E2Node:
      service_models:
---

# A topology kind representing an E2 cell
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: e2cell
spec:
  aspects:
    onos.topo.Location:
      lat: 50.08834
      lng: 14.40372
    onos.topo.E2Cell:
      cid: 0
      antenna_count: 1
      earfcn: 0
      cell_type: FEMTO
    onos.topo.Coverage:
      height: 0
      arc_width: 120
      azimuth: 0
      tilt: 0
---
# A topology kind representing an E2 termination point
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: e2t
spec:
  aspects: {}
---
# A topology kind representing one entity controlling another, e.g. E2T and E2NODE E2 connection relation
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: controls
spec:
  aspects: {}
---
# A topology kind representing one entity containing another, logically or physically, e.g. node-cell containment relation
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: contains
spec:
  aspects: {}
---
# A topology kind representing a neighbor relation, e.g. E2CELL neighboring another E2CELL
apiVersion: topo.onosproject.org/v1beta1
kind: Kind
metadata:
  name: neighbors
spec:
  aspects: {}
---