apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sdcore-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "sdcore-adapter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sdcore-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "sdcore-adapter.fullname" . }}
        {{- include "sdcore-adapter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SECURE
              value: "{{ .Values.secure }}"
            - name: CONFIG
              value: "{{ .Values.initialConfig }}"
            {{- range $key, $port := .Values.ports.gnmi }}
            - name: GNMI_{{ $key | upper }}_PORT
              value: {{ $port | quote }}
            {{- end}}
          ports:
            {{- range $key, $port := .Values.ports.gnmi }}
            - name: gnmi{{ $key }}
              containerPort: {{ $port }}
            {{- end}}
          readinessProbe:
            tcpSocket:
              {{ if .Values.secure }}
              port: {{ .Values.ports.gnmi.secure }}
              {{ else }}
              port: {{ .Values.ports.gnmi.insecure }}
              {{ end }}            
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              {{ if .Values.secure }}
              port: {{ .Values.ports.gnmi.secure }}
              {{ else }}
              port: {{ .Values.ports.gnmi.insecure }}
              {{ end }}

            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: targetconfig
              mountPath: /etc/sdcore-adapter/configs
              readOnly: true
            - name: secret
              mountPath: /etc/sdcore-adapter/certs
              readOnly: true              
            - name: logconfig
              mountPath: /etc/onos/config
              readOnly: true              
      volumes:
        - name: logconfig
          configMap:
            name: {{ template "sdcore-adapter.fullname" . }}-logconfig
        - name: targetconfig
          configMap:
            name: {{ template "sdcore-adapter.fullname" . }}-targetconfig            
        - name: secret
          secret:
            secretName: {{ template "sdcore-adapter.fullname" . }}-secret
