# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: onos-mho
description: ONOS MHO xAPP
kubeVersion: ">=1.17.0"
type: application
version: 0.3.5
appVersion: v0.3.5
keywords:
  - onos
  - sdn
  - ric
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
