# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: onos-exporter
description: ONOS KPIs Exporter
kubeVersion: ">=1.17.0"
type: application
version: 0.4.1
appVersion: v0.2.0
keywords:
  - onos
  - sdn
  - ric
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
