# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

global:
  image:
    registry: ""
    tag: ""

replicaCount: 1

image:
  registry: ""
  repository: onosproject/onos-exporter
  tag: v0.1.2
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-exporter"

service:
  exporter:
    port: 9861

config:
  onos-exporter:
    mode: "prometheus"
    e2tEndpoint: "onos-e2t:5150"
    xappPciEndpoint: "onos-pci:5150"
    xappKpimonEndpoint: "onos-kpimon:5150"
    
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
