# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

global:
  image:
    registry: ""
    tag: ""

replicaCount: 1

import:
  fluent-bit:
    enabled: false
  opensearch:
    enabled: false
  prometheus-stack:
    enabled: false

image:
  registry: ""
  repository: onosproject/onos-exporter
  tag: v0.2.0
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-exporter"

service:
  exporter:
    port: 9861

config:
  onos-exporter:
    mode: "prometheus"
    e2tEndpoint: "onos-e2t:5150"
    xappPciEndpoint: "onos-pci:5150"
    xappKpimonEndpoint: "onos-kpimon:5150"
    topoEndpoint: "onos-topo:5150"
    uenibEndpoint: "onos-uenib:5150"
    
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}

grafana:
  opensearch-datasources:
    - name: opensearch
      endpoint: https://opensearch-cluster-master:9200

  dashboards:
    - kubernetes-logs-pod.json
    - sdran.json
    - sdran-kpis.json

kube-prometheus-stack:
  grafana:
    plugins:
      - "grafana-opensearch-datasource"

opensearch:
  persistence:
    enabled: false
  opensearchJavaOpts: "-Xmx1g -Xms1g"
  resources:
    requests:
      cpu: "1000m"
      memory: "1000Mi"


opensearch-dashboards:
  persistence:
    enabled: false

fluent-bit:
  config:
    service: |
      [SERVICE]
          Flush 1
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020

    # https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          Tag kube.*
          Mem_Buf_Limit 128MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    # https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Cache_Use_Docker_Id On

    # https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Host opensearch-cluster-master
          Port 9200
          tls On
          tls.verify Off
          http_User admin
          http_Passwd admin
          Suppress_Type_Name On
          Logstash_Format On
          Logstash_Prefix fluentbit
          Time_Key @timestamp
          Replace_Dots On
          Generate_ID On
          Match kube.*
          net.connect_timeout         100
          net.keepalive               on
          net.keepalive_idle_timeout  300

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
        Name sdran
        Format regex
        Regex ^(?<timestamp>\d{4}-\d{2}-\d{2}.\d{2}:\d{2}:\d{2}.\d{3}).\s+(?<logLevel>\S+)\s+(?<process>\S+)\s+(?<file>\S+):(?<lineNo>\d+)\s+(?<log>.*)$
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
