# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oai-enb-du
  labels:
{{ tuple "oai-enb-du" . | include "oai-enb-du.metadata_labels" | indent 4 }}
spec:
  replicas: 1
  serviceName: oai-enb-du
  selector:
    matchLabels:
{{ tuple "oai-enb-du" . | include "oai-enb-du.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple "oai-enb-du" . | include "oai-enb-du.metadata_labels" | indent 8 }}
      {{- with index .Values "annotations" }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with index .Values "tolerations" }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "nodeSelector" }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      initContainers:
      - name: oai-enb-du-init
        image: {{ .Values.images.tags.oaidu | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        command:
        - /opt/oai/init_enb_du.sh
        env:
        - name: ENB_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /opt/oai/init_enb_du.sh
          name: script
          subPath: init_enb_du.sh
        - mountPath: /opt/oai/conf_files/du.conf
          name: config
          subPath: du.conf
        - mountPath: /opt/oai/share
          name: pod-share
      containers:
      - name: oai-enb-du
        image: {{ .Values.images.tags.oaidu | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
        command:
        - /opt/oai/run_enb_du.sh
        env:
        - name: ENB_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /opt/oai/run_enb_du.sh
          name: script
          subPath: run_enb_du.sh
        - mountPath: /opt/oai/share
          name: pod-share
      volumes:
      - name: config
        configMap:
          name: oai-enb-du
          defaultMode: 420
      - name: script
        configMap:
          name: oai-enb-du
          defaultMode: 493
      - name: pod-share
        emptyDir: {}