# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

global:
  image:
    registry: ""
    tag: ""

replicaCount: 1

images:
  tags:
    oaidu: docker.io/onosproject/oai-enb-du:v0.1.10
  pullPolicy: IfNotPresent

# Specify annotations (e.g., fluentbit/logging custom parser)
# annotations:
#   fluentbit.io/parser: oai

# Specify nodeSelector to pin oai-enb-du to worker nodes oaienb only
#
# nodeSelector:
#   node-role.test.org: oaienb

# Override NoSchedule for oai-enb-du to be scheduled on oaienb worker nodes
#
# tolerations:
#  - key: node-role.test.org
#    value: oaienb
#    effect: NoSchedule

config:
  oai-enb-du:
    log:
      level: "info"
      verbosity: "medium"
    enableUSRP: false
    radio:
      eutra_band: 7
      downlink_frequency: 2630000000L
      uplink_frequency_offset: -120000000
      rbs: 25
      max_rxgain: 125
      max_pdschReferenceSignalPower: -25
      rx_gain: 125
      tx_gain: 90
    mode: nfapi #or local_L1 for USRP and BasicSim
    networks:
      f1:
        interface: eno1
        address: 127.0.0.3/24
        portc: 500
        portd: 600
      nfapi:
        interface: eno1
        address: 127.0.0.3
        portc: 50001
        portd: 50011
  oai-enb-cu:
    enbID: 0xe00
    tac: 1
    plmnID:
      mcc: "208"
      mnc: "01"
      length: 2
    networks:
      f1:
        address: 127.0.0.2/24
        portc: 501
        portd: 601
  oai-ue:
    networks:
      nfapi:
        address: 127.0.0.4
        portc: 50000
        portd: 50010
  onos-e2t:
    enabled: yes
    networks:
      e2:
        address: 127.0.0.1/24
        port: 36421
