# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-rsm-5g.fullname" . }}-config
  labels:
    app: {{ template "onos-rsm-5g.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
{{- if .Values.logging }}
{{ toYaml .Values.logging | indent 4 }}
{{- end}}
  config.json: |-
{{ .Values.config.rsm.config_json | toPrettyJson | indent 4 }}
