# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oai-ue
  labels:
{{ tuple "oai-ue" . | include "oai-ue.metadata_labels" | indent 4 }}
spec:
  replicas: 1
  serviceName: oai-ue
  selector:
    matchLabels:
{{ tuple "oai-ue" . | include "oai-ue.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple "oai-ue" . | include "oai-ue.metadata_labels" | indent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with index .Values "tolerations" }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "nodeSelector" }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      initContainers:
      - name: oai-ue-init
        image: {{ .Values.images.tags.oaiue | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        command:
        - /opt/oai-ue/init_ue.sh
        volumeMounts:
        - mountPath: /opt/oai-ue/gen_ue_sim.sh
          name: script
          subPath: gen_ue_sim.sh
        - mountPath: /opt/oai-ue/init_ue.sh
          name: script
          subPath: init_ue.sh
        - name: config
          mountPath: /opt/oai-ue/conf_files/ue.conf
          subPath: ue.conf
        - name: config
          mountPath: /opt/oai-ue/conf_files/ue_sim.conf
          subPath: ue_sim.conf
        - mountPath: /opt/oai-ue/share
          name: pod-share
      containers:
      - name: oai-ue
        image: {{ .Values.images.tags.oaiue | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
        command:
        - /opt/oai-ue/run_ue.sh
        env:
        - name: UE_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: script
          mountPath: /opt/oai-ue/run_ue.sh
          subPath: run_ue.sh
        - name: pod-share
          mountPath: /opt/oai-ue/share
      volumes:
      - name: config
        configMap:
          name: oai-ue
          defaultMode: 420
      - name: script
        configMap:
          name: oai-ue
          defaultMode: 493
      - name: pod-share
        emptyDir: {}