# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onos-ric-ho.fullname" . }}
  labels:
    {{- include "onos-ric-ho.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "onos-ric-ho.fullname" . }}
      app: onos
      type: ho
      resource: {{ template "onos-ric-ho.fullname" . }}
      {{- include "onos-ric-ho.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "onos-ric-ho.fullname" . }}
        app: onos
        type: ho
        resource: {{ template "onos-ric-ho.fullname" . }}
        {{- include "onos-ric-ho.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: onos-ric-ho
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-caPath=/etc/onos/certs/tls.cacrt"
            - "-keyPath=/etc/onos/certs/tls.key"
            - "-certPath=/etc/onos/certs/tls.crt"
            - "-onosricaddr={{ index .Values "southbound.onos-ric.address" }}"
            - "-enableMetrics={{ default .Values.metrics.enabled .Values.enableMetrics }}"
            - "-hystCqi={{ .Values.hoParams.hystCqi }}"
            - "-a3offsetCqi={{ .Values.hoParams.a3OffsetCqi }}"
            - "-timeToTrigger={{ .Values.hoParams.timeToTriggerMs }}"
          livenessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: secret
              mountPath: /etc/onos/certs
              readOnly: true
            - name: config
              mountPath: /etc/onos/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "onos-ric-ho.fullname" . }}-secret
        - name: config
          configMap:
            name: {{ template "onos-ric-ho.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
