# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

# Default values for onos-e2sub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    registry: ""
    tag: ""
  storage:
    controller: ""
    consensus:
      name: ""

replicaCount: 1

image:
  registry: ""
  repository: onosproject/onos-e2sub
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-e2sub"

sctp:
  port: 36421

grpc:
  port: 5150

storage:
  controller: "atomix-controller.kube-system.svc.cluster.local:5679"
  consensus:
    enabled: true
    name: ""
    type: raft
    image: ""
    imagePullPolicy: IfNotPresent
    partitions: 1
    replicas: 1
    partitionsPerCluster: 1

service:
  # TODO: External NodePort service should be disabled by default
  external:
    nodePort:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
