apiVersion: v2
name: config-model-ric
version: 1.0.0
kubeVersion: ">=1.18.0"
appVersion: 1.0.0
description: RIC config model
keywords:
  - onos
  - sdn
  - config
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org