# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fb-kpimon-xapp.fullname" . }}
  labels:
  {{- include "fb-kpimon-xapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "fb-kpimon-xapp.fullname" . }}
      app: facebook
      type: kpimon
      resource: {{ template "fb-kpimon-xapp.fullname" . }}
  {{- include "fb-kpimon-xapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "fb-kpimon-xapp.fullname" . }}
        app: facebook
        type: kpimon
        resource: {{ template "fb-kpimon-xapp.fullname" . }}
    {{- include "fb-kpimon-xapp.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "kpimon/main.py"
            - "--ca-path=/etc/onos/certs/tls.cacrt"
            - "--key-path=/etc/onos/certs/tls.key"
            - "--cert-path=/etc/onos/certs/tls.crt"
            - "--e2t-endpoint={{ .Values.config.ric.e2tEndpoint }}"
            - "--path={{ .Values.config.servicePath }}/config.json"
            - "--topo-endpoint={{ .Values.config.ric.topoEndpoint }}"
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /status
              port: 8080
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: secret
              mountPath: /etc/onos/certs
              readOnly: true
            - name: config
              mountPath: {{ .Values.config.servicePath }}
              readOnly: false
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "fb-kpimon-xapp.fullname" . }}-secret
        - name: config
          configMap:
            name: {{ template "fb-kpimon-xapp.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
