# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

global:
  image:
    registry: ""
    tag: ""

replicaCount: 1

images:
  tags:
    oaiue: docker.io/onosproject/oai-ue:v0.1.11
  pullPolicy: IfNotPresent

# Specify annotations (e.g., fluentbit/logging custom parser)
# annotations:
#   fluentbit.io/parser: oai

# Specify nodeSelector to pin oai-ue to worker nodes oaiue only
#
# nodeSelector:
#   node-role.test.org: oaiue

# Override NoSchedule for oai-ue to be scheduled on oaiue worker nodes
#
# tolerations:
#  - key: node-role.test.org
#    value: oaiue
#    effect: NoSchedule

config:
  oai-ue:
    enableUSRP: false
    radio:
      max_rxgain: 125
      max_pdschReferenceSignalPower: -27
      carrier: 2630000000
      rbs: 25
      ue-rxgain: 120
      ue-txgain: 0
      ue-max-power: 0
    numDevices: 1 # support up to 3
    numRBs: 100 # support 25, 50, and 100
    syncTimer: 0 # interval to sync threads in lte UE
    numFramesRA: 30 # the number of Frames for RA
    device:
      imei: "356113022094149"
      manufacturer: "OAISIM"
      model: "OAISIM"
      pin: "0000"
    sim:
      msinStart: "4567891201" # for UE0 - will increase for next UEs
      apiKey: "465b5ce8b199b49faa5f0a2ee238a6bc"
      opc: "d4416644f6154936193433dd20a0ace0"
      msisdnStart: "1122334456" # for UE0 - will increase for next UEs
    networks:
      nfapi:
        interface: eno1
        address: 127.0.0.4
        portc: 50000
        portd: 50010
    log:
      level: "error"
      verbosity: "full"
  oai-enb-cu:
    plmnID:
      mcc: "208"
      mnc: "01"
      length: 2
      fullName: "ONF Aether"
      shortName: "Aether"
  oai-enb-du:
    networks:
      nfapi:
        address: 127.0.0.3
        portc: 50001
        portd: 50011
