# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onos-ric-mlb.fullname" . }}
  labels:
    {{- include "onos-ric-mlb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "onos-ric-mlb.fullname" . }}
      app: onos
      type: mlb
      resource: {{ template "onos-ric-mlb.fullname" . }}
      {{- include "onos-ric-mlb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "onos-ric-mlb.fullname" . }}
        app: onos
        type: mlb
        resource: {{ template "onos-ric-mlb.fullname" . }}
        {{- include "onos-ric-mlb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: onos-ric-mlb
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "onos-ric-mlb.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-caPath=/etc/onos/certs/tls.cacrt"
            - "-keyPath=/etc/onos/certs/tls.key"
            - "-certPath=/etc/onos/certs/tls.crt"
            - "-onosricaddr={{ .Values.southbound.onosRic.address }}"
            - "-enableMetrics={{ default .Values.metrics.enabled .Values.enableMetrics }}"
            - "-threshold={{ .Values.mlbParams.mlbThreshold }}"
            - "-period={{ .Values.mlbParams.mlbPeriod }}"
          startupProbe:
            tcpSocket:
              port: 5150
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5150
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: secret
              mountPath: /etc/onos/certs
              readOnly: true
            - name: config
              mountPath: /etc/onos/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "onos-ric-mlb.fullname" . }}-secret
        - name: config
          configMap:
            name: {{ template "onos-ric-mlb.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
