# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v2
name: ran-simulator
description: ONOS RAN Simulator
kubeVersion: ">=1.15.0"
type: application
version: 0.0.7
appVersion: v0.6.7
keywords:
  - onos
  - sdn
  - ran
home: https://onosproject.org
maintainers:
  - name: Sean Condon
    email: sean@opennetworking.org
