{
 "title": "SDCore Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "slice",
    "query": {
     "query": "label_values(smf_pdu_session_profile, slice)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VCS UE Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (state,slice) (smf_pdu_session_profile{slice=~\"$slice\"})",
     "legendFormat": "{{slice}}-{{state}}"
    }
   ]
  },
  {
   "title": "UE Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "smf_pdu_session_profile{slice=~\"$slice\"}==1"
    }
   ]
  },
  {
   "title": "VCS Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (slice) (ue_throughput{direction=\"upstream\",slice=~\"$slice\"})",
     "legendFormat": "{{slice}} upstream"
    },
    {
     "expr": "sum by (slice) (ue_throughput{direction=\"downstream\",slice=~\"$slice\"})",
     "legendFormat": "{{slice}} downstream"
    }
   ]
  },
  {
   "title": "VCS Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (slice) (ue_latency{direction=\"upstream\",slice=~\"$slice\"})",
     "legendFormat": "{{slice}} upstream"
    },
    {
     "expr": "sum by (slice) (ue_latency{direction=\"downstream\",slice=~\"$slice\"})",
     "legendFormat": "{{slice}} downstream"
    }
   ]
  }
 ]
}